version: '3'

services:
  jenkins:
    restart: unless-stopped # always, no, on-failure, on-failure:3, unless-stopped
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - FTP_PROXY=${FTP_PROXY}
    env_file:
      - .env
    volumes:
      - ./data/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    ports:
      - '8080:8080'
      - '50000:50000'